BaseDir/laundryManagementSystem/company/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='demo.html')),
]

BaseDir/laundryManagementSystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from laundryManagementSystem.company import views as company_views
from laundryManagementSystem.customer import views as customer_views
from django.views.generic import TemplateView
from laundryManagementSystem.laundryman import views as laundry_views
from laundryManagementSystem.demo import views as demo_views
from django.conf import settings
from django.conf.urls.static import static
from laundryManagementSystem.addtocart.views import PricingView, DemoView, AddedToCart, MyCartView, ManageCartView, EmptyCartView, CheckoutView
from laundryManagementSystem.addtocart import views as addtocart_views
from laundryManagementSystem.demo.views import HomeView, CustomDetailView, TestingRESTAPI
from laundryManagementSystem.addtocart.views import AddedOrderItems
from django.urls import path
from laundryManagementSystem.RESTfulAPI import views as RESTfulAPI_views
from rest_framework import routers
from rest_framework.authtoken import views
from laundryManagementSystem.company.views import CompanyProfileView  
from django.contrib.auth import views as auth_views
from laundryManagementSystem.Payment import views as payment_views
from django.views.static import serve
  
router = routers.DefaultRouter()
router.register(r'rest6', RESTfulAPI_views.ProductViewSet)
# Here above we register our router which accept two argument first one is 
# the REST url preffix('inamaanisha url inayoanzia rest6' ni rest6 sio rest5 or rest)
# second is  our view set


# The combination of viewset and router automatically create a sensitive
# REST end points (e.g. delete and update) which by default are accessible
# to anyone
  
# REMEMBER THE REST SERVICE END POINT (is the url loaded to browser)
urlpatterns = [
    path('forTestingAutomationGmail/', TemplateView.as_view(template_name='testTingDropDownListAutomation.html')),
    # Tomorrow I will try to put my customer logout logics
    path('changedNo/', addtocart_views.changedNo, name = "changed"),
    path('updatingStatus<int:order_id>', laundry_views.orderCompleted, name="updatingStatusToCompleteForLaundryman"),
    path('updatingStat<int:order_id>', company_views.orderCompleted, name="updatingStatusToComplete"),
    path('realseeLauNoti<int:notification_id>', laundry_views.realseelaunotification, name="realseelaunotification"),
    path('deleteOrder<int:order_id>/', customer_views.deleteOrder, name="deleteOrder"),    # this is the view for deleting post, for now I disallowed the customer/laundryman/company to delete the order since the order records should be kept
    path('customerOrders/', customer_views.ViewOrders.as_view(), name="displayMyOrderes"),
    path('editCustomerProfile/', customer_views.changeProfile, name="changeCustomerProfile"),
    path('customerProfile/', customer_views.customerProfile, name="customergetProfile"),
    path('confirmed/', TemplateView.as_view(template_name="payment/confirm.html"), name="confirmedPosted"),
    path('changeNamba/', TemplateView.as_view(template_name='payment/changeno.html'), name="doUWantToChangeIt"),
    path('finishHim/', addtocart_views.succeedPayment, name="finishHim"),  
    path('handlingPaymentNumber/', payment_views.handlingPaymentNumber, name = "pay"),  
    path('clickPay/', payment_views.get_jsonResponse, name="payButton"),
    path('paymentAPI/', RESTfulAPI_views.payment, name="paymentAPI"),
    path('changePassword/', company_views.PasswordChangeView.as_view(template_name='company/changePassword.html'), name="forgotPassword"),
    path('password_success/', company_views.password_success, name = "password_success"),
    path('deleteInformation/<int:notification_id>/', company_views.deleteNotification, name="deleteNotification"),
    path('viewCompNotification<int:notification_id>/', company_views.realseenotification, name = "viewCompNotification"),  # nahisi hii nimeitumia kotekote kwa laundryman and company to view the notification
    path('lauNotification/', laundry_views.viewNotification, name = "lauNotification"),
    path('compNotification/', company_views.viewNotification, name="compNotification"),
    path('editingLauProfile/', laundry_views.changeProfileForm, name="editLauProfile"),
    path('editingCompProfile/', company_views.changeProfileForm, name="editCompProfile"),
    path('comwallet/', TemplateView.as_view(template_name="company/walet.html"), name="comWallet"),
    path('comreceivedOrder/', company_views.ViewOrders.as_view(), name="com_received_order"),  
    path('lauwallet/', TemplateView.as_view(template_name='laundryman/i_walet.html'), name="lauWallet"),
    path('laureceivedOrder/', laundry_views.ViewOrders.as_view(), name="received_order"),  
    path('viewCompanies/', company_views.companiesView, name = "listOfCompanies"),  
    path('viewLaundries/', company_views.laundriesView, name = "listOfLaundries"),
    path('option/', TemplateView.as_view(template_name = 'login_as.html'), name="chagua"),
    path('logREST/', views.obtain_auth_token, name = "login"),
    path('loginREST/', RESTfulAPI_views.LoginView.as_view(), name = "login"),
    path('users/', RESTfulAPI_views.UserCreate.as_view(), name="user_create"),
    url(r'^rest-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^rest6/', include(router.urls)),
    path('rest5/', RESTfulAPI_views.UsingMixinProductList.as_view(), name='usingMixinsAsBoilerPointToReduceCode'),
    path('rest4/', RESTfulAPI_views.ProductList.as_view(), name= 'classBasedAPIView'),
    path('rest3/', RESTfulAPI_views.rest3, name= 'usingRestFramework2'),
    path('rest2/', RESTfulAPI_views.rest2, name= 'usingRestFramework'),
    path('rest/<int:product_id>/', RESTfulAPI_views.rest_cartproduct, name='detail'),
    path('demo2/', TestingRESTAPI.as_view(), name="api_test"),
    url(r'^rest/$', RESTfulAPI_views.rest_cart, name ='api'), 
    url(r'^scheduled/$', addtocart_views.scheduled, name="scheduled"),
    path('placedTo/', addtocart_views.placedTo, name = 'whoassigned'),
    path('checkout/', addtocart_views.checkout, name="checkout"),
    path('empty-cart/', EmptyCartView.as_view(), name="emptycart"),
    path('manage-cart/<int:cp_id>/', ManageCartView.as_view(), name="managecart"),
    path('mycart/', MyCartView.as_view(), name="mycart"),
    path("realaddedtocart-<int:pro>/", AddedToCart.as_view(), name="realaddtocartbtn"),
    path('awesome/', TemplateView.as_view(template_name = 'product/added2.html'), name='keepmoving'),
    path('addedornot/<title>/', addtocart_views.add_to_cart, name="itemisaddedornot"),
    path('addToCart/<int:pk>/', DemoView.as_view(), name="add_to_cart"),
    path('itemlist/', AddedOrderItems.as_view(), name="itemlist"),
    # hii pattern hapa inakataa ko ni bora utumie path ku-render these additional info in urls
    #    url('r^details/(?P<pk>\d+)/$', CustomDetailView.as_view(), name="details"),
    # this is how we add additional argument in url using the path library
    path('details/<int:pk>', CustomDetailView.as_view(), name="details"),
    # any templateView customized class should contains as_view() method
    path('pricing/<int:migo>/', PricingView.as_view(), name="pricing"),
    url(r'^demo/$', HomeView.as_view(), name="demo"),  
    url(r'^index2/results/$', company_views.search),  
    url(r'^results/$', company_views.search, name="searched_list"),
    url(r'^test2/$', TemplateView.as_view(template_name='signup.html'), name="secondEncounteredInterface"), #2
    url(r'index2/$', TemplateView.as_view(template_name = 'option.html'), name="viewLaundersAfterLogin"),   #wafuaji
    url(r'company/profile/$', company_views.profile, name="nolimit"), 
    url(r'company/register/$', company_views.register, name="jisajili"),   
    #url(r'tests/$', company_views.pricing, name="pricing"),
    url(r'viewcompanyprofile/$', CompanyProfileView.as_view(template_name='company/company_profile.html'), name="company_profile"), # hapa inakuja kukaa profile aliyokupa thabiti 
    url(r'viewprofile/$', laundry_views.LaundryProfileView.as_view(template_name='laundryman/individual_profile.html'), name="profile222"),  # Hapa inakuja kukaa profile aliyokupa thabiti
    url(r'test/$', TemplateView.as_view(template_name='laundryman/realprofile.html')),
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='localhost'),   # 1
    url(r'customer/login/$', customer_views.customerlogin, name="customer_login"),
    url(r'company/login/$', company_views.companylogin, name="company_login"),
    url(r'laundry/login/$', laundry_views.laundrylogin, name="laundry_login"),
    url(r'laundry/profile/$', laundry_views.profile,  name="profile"),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'laundry/register/$', laundry_views.register),
    url(r'accounts/logout/$', customer_views.logout_request, name = "logout"),
    #url(r'accounts/', include('allauth.urls')),   
    url(r'^customer/demo/$', customer_views.registerDemo),  
    url(r'^customer/signup/$', customer_views.register),
    #url(r'^company/signup/$', company_views.signUp),
    url(r'^company/$', include('laundryManagementSystem.company.urls')),
    url(r'^admin/', admin.site.urls, name="/"),  
    url(r'^test0/$', TemplateView.as_view(template_name="font&booteffects.html")),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html'), name="password_reset_complete"),

]


if settings.DEBUG:  

BaseDir/laundryManagementSystem/RESTfulAPI/models.py
from django.db import models

# Create your models here.
 

BaseDir/laundryManagementSystem/addtocart/models.py
from django.db import models
from ..customer.models import UserProfile0
from django.contrib.auth.models import User
import datetime
from datetime import timedelta
import random
#from django.contrib.postgres.fields.jsonb import JSONField
import string  
from jsonfield import JSONField
 
delta = timedelta(days=2)
finished_time = datetime.datetime.now() + delta

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(UserProfile0, on_delete=models.CASCADE)


    def __str__(self):
        return user.user

class Product(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')
    price = models.PositiveIntegerField()
    quantity = models.IntegerField(default=1)
 
    def __str__(self):
        return self.title



         
# If I set null=True and blank=True here on the cart it means there
# is no login required to create a cart
class Cart(models.Model):
    # on naming use _ like ref_no not - like ref-no it will
    # throw syntax error
    #ref_no = models.CharField(max_length=200)

    customer = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    is_ordered = models.BooleanField(default=False)
    arrived_at = models.DateTimeField(default=datetime.datetime.now(), null=True, blank=True)
    finished_at = models.DateTimeField(default=finished_time, null=True, blank=True)
    assigned_To = models.CharField(max_length=50, blank=True, null=True)
    options = (
        ("Pick at station", "Pick at station"),
        ("Door step pickup", "Door step pickup"),
    )
    mode = models.CharField(max_length=100, choices=options, blank=True, null=True, default="Pick at station")
  
 

class CartProduct(models.Model): 
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    date_ordered = models.DateTimeField(auto_now_add=True, null=True)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    def __str__(self):
        return self.product.title

ORDER_STATUS = (
    ("Working on it", "Working on it"),
    ("Completed", "Completed"),
)



location = (
    ('Ilala', 'Ilala'),
    ('Kinondoni', 'Kinondoni'),
    ('Temeke', 'Temeke'),
    ('Ubungo', 'Ubungo'),  
    ('Kigamboni', 'Kigamboni')
)
class Order(models.Model):
    assignedTo = models.CharField(max_length=200, null=True, blank=True)
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.ForeignKey(User, related_name = 'ordered_set', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    mobile = models.PositiveIntegerField(null=True, blank=True)
    email = models.CharField(max_length=50, null=True, blank=True)
    order_status = models.CharField(max_length=200, choices=ORDER_STATUS, default="Working on it")
    created_at = models.DateTimeField(auto_now_add=True)
    district = models.CharField(max_length=200, choices = location, null=True, blank=True)
    ward = models.CharField(max_length = 200, null=True, blank=True)
    street = models.CharField(max_length = 200, null=True, blank=True)
    zipcode = models.PositiveIntegerField(null=True, blank=True)
    orderID = models.CharField(max_length=25, null=True, blank=True)
    def __str__(self):
        return "Order: "+str(self.id)

    

class Post(models.Model):
    head = models.CharField(max_length=50)
    body = models.CharField(max_length=200)
    sender = models.CharField(max_length=30, default="admin", null=True, blank=True)
    receiver = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    contact = models.IntegerField(null=True, blank = True)
    code = models.IntegerField(null=True, blank=True)
    district = models.CharField(max_length=200, null=True, blank=True)
    ward = models.CharField(max_length=200, null=True, blank=True)
    street = models.CharField(max_length=100, null=True, blank=True)
    physical_address = models.CharField(max_length=200, null=True, blank=True)
    total = models.PositiveIntegerField(null=True, blank=True)
    startDate = models.DateTimeField(null=True, blank=True)
    finishDate = models.DateTimeField(null=True, blank=True)
    items = JSONField(null=True, blank=True)
    quantity = models.CharField(max_length=100, null=True, blank=True)
    mode = models.CharField(max_length=100, null=True, blank=True)
    clicked = models.BooleanField(default=False, null=True, blank = True)  # this means by default all the post is non-clicked we will set it clicked when the user view/click the notification.
    def __str__(self):
        when = self.created_at.strftime("%Y-%m-%d %H:%M")
        return "Its created at: "+ when

BaseDir/laundryManagementSystem/Payment/forms.py
from .models import Payment
from django import forms



class PaymentForm(forms.ModelForm):
    """Form definition for Payment."""

    class Meta:
        """Meta definition for Paymentform."""
        
        model = Payment
        fields = ['account_number']

BaseDir/laundryManagementSystem/addtocart/forms.py
from .models import Product, Order
from django import forms


class ProductQuantityForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['quantity']

class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['district', 'mobile', 'address', 'ward', 'street','zipcode']

BaseDir/laundryManagementSystem/demo/forms.py
from .models import Post
from django import forms
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'author')


        

BaseDir/laundryManagementSystem/demo/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import PostForm
from .models import Post
from laundryManagementSystem.addtocart.models import CartProduct
from django.views.generic import ListView, DetailView, TemplateView
# Create your views here.

class HomeView(ListView):
    model = Post
    template_name = 'homedemo.html'



class CustomDetailView(DetailView):
    model = Post
    template_name = "details.html"
  


"""
def home(request):
    return render(request, 'homedemo.html', {})
"""
"""
def demo(request):
    if request.method == 'POST':
        demo = DemoForm(request.POST)

        username = request.GET.get('username')
        print(username)
        
        password = request.GET.get('password')
        print(password)

       
        if demo.is_valid():
            # Here after getting these post values
            # use queries to create the object instance

            Demo.objects.create(
                username = request.POST.get('username'),
                password = request.POST.get('password')
            )

            print('You are good bro!')

            return HttpResponseRedirect('/index2/')
        
    else:
        demo = DemoForm()
        
    context = {'demo': demo}
    print(request.POST.get('username'))
    print(request.GET.get('passwords'))
    return render(request, 'demo/demo.html', context)
"""

class TestingRESTAPI(TemplateView):
    template_name = 'apidemo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['id'] = 2 
        return context  

BaseDir/laundryManagementSystem/templates/addtocart/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id = "msg" role="alert">
            <div class="text-center" style="background-color: #f7a072; margin-left: 0px; margin-right: 0px;"> {{ message }} </div>
        </div>
    {% endfor %}
{% endif %}

BaseDir/laundryManagementSystem/templates/addtocart/mycart.html
{% extends 'base0.html' %}
{% block carticon %}
    <i class="fas fa-shopping-cart fa-2x mx-2"></i>
{% endblock %}


{% block content %}

 
  {% include './messages.html' %}
    <div class="container">
        <div class="row">
            {% if cart.cartproduct_set.all %}
            <div class="col-md-8 table table-bordered coolers">
              <div style="font-size: 30px;" class="font-weight-bold text-center">Your laundry cart</div>              
                <div class="text-center mb-1"> <a href="{% url 'pricing' migo=id %}" class="btn  d-inline btn-primary"><i class="fas fa-arrow-left mx-2"></i>Continue adding to cart</a> </div>
                <div class="text-center"><i class="far fa-handshake fa-2x mx-3 mt-4"></i>Job assigned to : <span class="font-weight-bold text-primary">{{name}}</span></div>  
                <!-- Hapa nimeweka cart.id ili niweze hii link ifanye kazi lakn hapa inabidi hii cart iwe na id ya laundry/company placed to process the customer orders -->

                <hr>
                
                <table  class="table table-borderless">
                <thead>
                    <tr>  
                        <th></th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                {% for cp in cart.cartproduct_set.all %}
                <tbody>
                <tr>
                    <td><img src="{{cp.product.image.url}}" class="gotgo"></td>
                    <td><span"> {{cp.product.title}}</span></td>
                    <td><a href="{% url 'managecart' cp.id %}?action=dcr"><i class="fas fa-caret-left fa-2x mx-2"></i></a><span class="fit">{{cp.quantity}}</span><a href="{% url 'managecart' cp.id %}?action=inc"><i class="fas fa-caret-right fa-2x mx-2"></i></a></td>
                    <td><span class="fit">Tshs. {{cp.subtotal}}</span></td>
                    <td><div style="text-align:center;" class="punguza"><a class="btn btn-danger" href="{% url 'managecart' cp.id %}?action=rmv"><i class="fas fa-times"></i></a></div></td>

                </tr>

                {% endfor %}
                
                <tr>
                    <th colspan="3" class="text-right">Total</th>
                    <th>Tshs.{{cart.total}}</th>
                    <!--{% if cart.cartproduct_set.all %}--> <!-- this will check if there is any queryset of cartproduct related to carts-->
                    <th colspan="3.5" class="text-right"><a href="{% url 'emptycart' %}" class="btn btn-danger">empty cart</a></th>
                    <!--{% endif %}-->
                </tr>
                
                </tbody> 
                </table>

                <hr>
                <!--{% if cart.cartproduct_set.all  %}-->
                <div class="col-md-4 checkout d-flex">
                    <a href="{% url 'checkout' %}" class="btn btn-success justify-content-end d-block">Proceed to checkout<i class="fas fa-arrow-right mx-2"></i></a> 
                </div>

                
                <!--{% endif %}-->
            </div>
                <!--{% if cart.cartproduct_set.all %}-->
                <div class="col-md-5 mar mx-3" style="background-color: white;">
                    <form action="{% url 'scheduled' %}" method = "POST" class="needs-validation" novalidate>
                            {% csrf_token %}
                            <p class="font-weight-bold" style="margin-top: 25px;"> Here you can schedule on when to take job(submit dirt clothes/shoes) with its completion date (a date on for job to be done), defaulted to 2 days as due time for less than 21 number of clothes or/and shoes, any job is assumed to be done on duration of 2 days to 15 days depending on schedule and amount of clothes/shoes </p>
                            <hr>
                            <div class="row mx-3">
                                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                                <div class="input-group mb-2">
                                  <div class="input-group-prepend">
                                    <div class="input-group-text">arrive date</div>
                                  </div>
                                  <input type="text" class="form-control" id="picker1" name="start" value="{{start}}" required>
                                </div>
                            </div>
                            <div class="row mx-3">
                                <label class="sr-only" for="inlineFormInputGroup">Username</label>
                                <div class="input-group mb-2">
                                  <div class="input-group-prepend">
                                    <div class="input-group-text">finish date</div>
                                  </div>
                                  <input type="text" class="form-control" id="picker2" name="end" value="{{end}}" required>
                                  <!--remember this above id we use it on js, and remember id is only applied at once unlike the class, so to use this features on the other element we need another id-->
                                </div>
                            </div>
                            
                    
                             
                            <p class="font-weight-bold" style="margin-top: 20px;"> Here you can select the mode of collecting already processed clothes either to go yourself to pick them at the working station or to enable a door-to-door delivery </p><hr>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault1" value = "Pick at station" checked>
                                <label class="form-check-label" for="flexRadioDefault1">
                                  Pick at a station
                                </label>
                              </div>
                              <div class="form-check">
                                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" value = "Door step pickup">
                                <label class="form-check-label" for="flexRadioDefault2">
                                  Door step pickup
                                </label>
                              </div> 
                            <button type="submit" class="btn btn-primary arr">save</button>
                      </form>
                </div>
                {% else %}
                <p style="margin-top: 30px;"> Ooops!!! Empty cart,<br>You don't have any clothes or shoes added to cart, if you wish, click link below to add items to your cart </p>
                <a href="{% url 'pricing' migo=id%}" class="btn btn-secondary" style = "margin-bottom: 279px;">Items listing</a>
                <!-- Hapa nimeweka cart.id ili niweze hii link ifanye kazi lakn hapa inabidi hii cart iwe na id ya laundry/company placed to process the customer orders -->
                {% endif %}   
            {% else %}  <!-- This means the cart is not found, it will return-->
            <p style="margin-top: 30px;"> Ooops!!! Empty cart,<br>You don't have any clothes or shoes added to cart, if you wish, click link below to add items to your cart </p>
            <a href="{% url 'pricing' migo=id%}" class="btn btn-secondary" style = "margin-bottom: 279px;">Items listing</a>
            <!-- Hapa nimeweka cart.id ili niweze hii link ifanye kazi lakn hapa inabidi hii cart iwe na id ya laundry/company placed to process the customer orders -->

            {% endif %}
        </div>
    </div>
{% endblock %}